INSERT INTO Skill (skill_name, position) VALUES ('Java', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('JavaScript', 'frontend');
INSERT INTO Skill (skill_name, position) VALUES ('Python', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Ruby', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('C#', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('PHP', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Node.js', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('React', 'frontend');
INSERT INTO Skill (skill_name, position) VALUES ('Angular', 'frontend');
INSERT INTO Skill (skill_name, position) VALUES ('Vue.js', 'frontend');
INSERT INTO Skill (skill_name, position) VALUES ('Spring Boot', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Express.js', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Django', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Laravel', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Ruby on Rails', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('ASP.NET', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Flask', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Symfony', 'backend');
INSERT INTO Skill (skill_name, position) VALUES ('Ember.js', 'frontend');

